name: Lint and Test

on:
  push:
    branches:
      - main
      - feature/*  # Optional: run on feature branches
  pull_request:
    branches:
      - main
      - feature/*

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install

      - name: Run Lint
        run: |
          npx eslint . # Assuming you have ESLint configured

  test:
    runs-on: ubuntu-latest
    needs: lint  # This ensures linting runs before tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install

      - name: Run tests
        run: |
          npm test # Assuming you have tests configured (Jest, Mocha, etc.)
